### PR TITLE
Update markerclusterer.js

### PR DESCRIPTION
**Pull request by aobjects**
Google took their files off their servers and put them on GitHub. We're using this package and we would like it to auto update for all of our devs.

### CODE REVIEW

**Comment by proft** [comment]
oakworks, please, accept this pull request

**Comment by proft** [comment]
quick fix: add ``MarkerClusterer.prototype.MARKER_CLUSTER_IMAGE_PATH_ = 'https://cdn.rawgit.com/googlemaps/js-marker-clusterer/gh-pages/images/m'; `` to client part

**Comment by PeterTheOne** [comment]
You don't need to update `MARKER_CLUSTER_IMAGE_PATH_`, you can just set the `imagePath` option to the path of the local images.

**Comment by aobjects** [comment]
That's fine we can look at doing that, but then your code is broken out of
the box along with the upstream clusterer.

**Comment by steve-ross** [comment]
Wow sorry this slipped through the cracks for so long

**Comment by steve-ross** [comment]
closing, you can change the url manually.

**Pull request closed without merging**
